### ISSUE TITLE
send people to rootless docker docs

### ISSUE THREAD

**Issue by martinpospech** [tqtezos/assets.tqtezos.com#32]
Running docker in rootless mode is not obvious, but seems to work fine. It's a good idea to link people to the specific docker article from the flextesa setup docs.

https://docs.docker.com/engine/security/rootless/#distribution-specific-hint

![Screenshot_20210129_200701](https://user-images.githubusercontent.com/10012815/106317038-fa95a300-626d-11eb-8926-1aea7de27173.png)

**Comment by smondet** [comment]
The "rootless" doc is about running the docker daemon as a regular user; that's pretty advanced and not necessary at all, why would we put that in the beginner tutorials?

**Comment by itkach** [comment]
I agree

**Comment by martinpospech** [comment]
People who are not familiar with docker don't know how their setup should
look. Running in rootless mode is better, unless it breaks something. So it
makes sense to point the readers in the right direction.

I am using rootless docker with flextesa and nothing seems obviously
broken. Is there a downside?

**Comment by itkach** [comment]
>  Is there a downside? 

The downside, at the very least, is added complexity that is irrelevant to and distracts from learning Tezos.
