### ISSUE TITLE
Homebrew install steps out of date

### ISSUE THREAD

**Issue by Git-on-my-level** [tqtezos/assets.tqtezos.com#37]
The Mac OS Tezos client install instructions reference this Homebrew tap: https://github.com/tqtezos/homebrew-tq.git

However the tap seems to be no longer maintained. As many users are likely to be using Mac OS and trying to install `tezos-client` locally, this should be updated to something more up to date, like the releases here: https://github.com/serokell/tezos-packaging

**Comment by rvem** [comment]
Tap in `tezos-packaging` is currently a bit broken, see https://github.com/serokell/tezos-packaging/issues/134. Let's not update the documentation until the aforementioned bug is resolved :)

**Comment by fredcy** [comment]
I just gave homebrew a try and it installed tezos-node version 7.2 and no Edo executables.  That's not useful.
